name: planets
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  provider: ^6.0.2
  flutter_screenutil: ^5.3.1
  delayed_display: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_fadein: ^2.0.0
  drop_shadow_image: ^0.9.1
  flutter_sliding_tutorial: ^1.1.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/
    - assets/img_planets/