name: planets
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_screenutil: ^5.3.1
  delayed_display: ^2.0.0
  carousel_slider: ^4.0.0
  auto_size_text: ^3.0.0
  bottom_sheet: ^2.0.0
  get_storage: ^2.0.3
  easy_rich_text: ^1.0.4
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/
    - assets/img_planets/
    - assets/icons/